name: CI

on:
  push:

env:
  TURBO_TOKEN: ${{secrets.TURBO_TOKEN}}
  TURBO_TEAM: ${{vars.TURBO_TEAM}}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup requirements
        uses: ./.github/actions/setup
      - name: Run tests
        run: pnpm test
